name: Add Update Label Weekly - ATO

# Customization notes:
# CUSTOMIZE: Change cron. Currently runs Fri 0700 UTC, exc. July and December
#    ⮡ You can compose a schedule here: https://crontab.cronhub.io/

on:
  schedule:
    - cron: '0 7 * 1-6,8-11 5' # ⓵
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode without posting comments or updating issues'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  Add-Update-Label-Weekly:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run workflow
        uses: t-will-gillis/automate-the-org/gha-add-update-label-weekly@test-resolve-label-ref12
        with:
          github-token: ${{ secrets.HACKFORLA_GRAPHQL_TOKEN }}
          dry-run: ${{ github.event.inputs.dry-run || 'true' }}
