name: Comment when opened
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          
          
  comment2:
    runs-on: ubuntu-latest
    steps:
      - run: echo " This job was automatically triggered by  ${{ github.event_name }} ."
      - run: echo " This job was automatically triggered by  ${{ github.event.project }} ."
      - run: echo " This  job was automatically triggered by  ${{ github.project_card }} ."
      - run: echo " This  job was automatically triggered by  ${{ github.project }} ."
      - run: echo " This  job was automatically triggered by  ${{ github.project_name }} ."
