name: Create Issues from Template

# This action is for creating many issues at once using a source file and a template created 
on:
  workflow_dispatch:

jobs:
  Create-Issues-From-Template:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'

    steps:
    # Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Trims inactive members from team and notifies idle members
    - name: Read Source File
      id: read-source-file
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/utils/_create-issues-from-template/create-issues-from-template.js')
          script({ g: github, c: context })
