name: Find Start Date

on:
  workflow_dispatch:

jobs:
  Find_Start_Date:
    runs-on: ubuntu-latest
    # optional line
    if: github.repository == 't-will-gillis/website'

    steps:
      - name: Retrieve Repo
        id: retrieve-repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          script: |
            const OWNER = 'hackforla'
            const REPO = 'website'
            return results = await github.request('GET /repos/{owner}/{repo}', {
              owner: OWNER,
              repo: REPO
            })
      
            
      - name: Print Results
        run: |
          echo ${{ steps.retrieve-repo.outputs.result }}
            
            
