name: Create Issues 6454

# This action runs at 11:00 UTC/ 4:00 PDT on the first day of every month except January and August.
on:
  workflow_dispatch:

jobs:
  Create-Issue:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'

    steps:
    # Checkout repo, and provide authorization token for `stefanzweifel/git-auto-commit-action` below
    - name: checkout
      uses: actions/checkout@v4

    - name: Create Issue
      id: create-issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/trigger-schedule/list-inactive-members/for-6454.js')
          script({g: github, c: context})
