name: GraphQL Query 4
on: 
  workflow_dispatch:

jobs:
  Get-Nodes:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.GRAPHQL }}
          USER: "t-will-gillis"
          PROJECT_NUMBER: 5

        run: |
          gh api graphql -f query='
            query{
              node(id: "PVT_kwHOAm6MB84Aiu3X") {
                  ... on ProjectV2 {
                    items(first: 20) {
                      nodes{
                        id
                        fieldValues(first: 8) {
                          nodes{                
                            ... on ProjectV2ItemFieldTextValue {
                              text
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldDateValue {
                              date
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              name
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                          }              
                        }
                        content{              
                          ... on DraftIssue {
                            title
                            body
                          }
                          ...on Issue {
                            title
                            assignees(first: 10) {
                              nodes{
                                login
                              }
                            }
                          }
                          ...on PullRequest {
                            title
                            assignees(first: 10) {
                              nodes{
                                login
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }'
