name: GraphQL- Get Status Fields 2
on: 
  workflow_dispatch:

jobs:
  Get-Nodes:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.GRAPHQL }}

        run: |
          gh api graphql -f query='
            query findStatusSubfieldIds($login:String!, $number:Int!) {
              organization(login:$login) {
                projectV2(number:$number) {
                 field(name:"Status") { 
                    ... on ProjectV2SingleSelectField { 	
                    id
                    name
                    options{ 
                        id 
                        name
                      } 
                    }
                  }
                }
              }
            }
          ' -F login="hackforla" -F number=86
                 
