name: GraphQL Query 3
on: 
  workflow_dispatch:

jobs:
  Get-Nodes:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.GRAPHQL }}
          USER: "t-will-gillis"
          PROJECT_NUMBER: 5

        run: |
          gh api graphql -f query='
            query {
              repository(owner:"t-will-gillis", name:"website") {
                issues(last:20, states:CLOSED) {
                  edges {
                    node {
                      title
                      url
                      status
                      labels(first:5) {
                        edges {
                          node {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            }'
