name: GraphQL Query 5
on: 
  workflow_dispatch:

jobs:
  Get-Nodes:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.GRAPHQL }}
          USER: "t-will-gillis"
          PROJECT_NUMBER: 5

        run: |
          gh api graphql -f query='
            query findStatusSubfieldIds($login:String!, $number:Int!) {
              organization(login:$login) {
                projectV2(number:$number) {
                 field(name:"Status") { 
                    ... on ProjectV2SingleSelectField { 	
                    id
                    name
                    options{ 
                        id 
                        name
                      } 
                    }
                  }
                }
              }
            }',
            {
              login: "hackforla",
              number:86
            }
                        
