name: GraphQL Query 7

on:
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Run GraphQL query
        env:
          GITHUB_TOKEN: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
        run: |
          echo "Running GraphQL query"
          QUERY='
            query {
              repository(owner:"t-will-gillis", name:"website") {
                projectV2(number:5){
                  items(first:10 ){
                    pageInfo{ hasNextPage }
                    nodes{
                      fieldValueByName(name:"Status"){
                        __typename
                        ... on ProjectV2ItemFieldSingleSelectValue{
                          id
                          name
                        }
                      }
                      content{
                        __typename
                        ... on Issue{
                          number
                          title
                          id
                        }
                      }
                    }
                  }
                }
              }
            }
            '
          curl -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "{\"query\": \"$QUERY\"}" https://api.github.com/graphql
