name: GraphQL- Get Status Fields
on: 
  workflow_dispatch:

jobs:
  Get-Nodes:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.GRAPHQL }}

        run: |
          gh api graphql -f query='
            query findStatusSubfieldIds {
              organization(login:"hackforla") {
                projectV2(number:86) {
                 field(name:"Status") { 
                    ... on ProjectV2SingleSelectField { 	
                    id
                    name
                    options{ 
                        id 
                        name
                      } 
                    }
                  }
                }
              }
            }'
                        
