name: Graph QL Trigger Status

on:
  workflow_dispatch:

jobs:
  Setup-GraphQL-Query:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          
      - name: Start Query
        id: start-query
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/utils/graphql-status-6.js')
            script({g: github, c: context})
