name: Test Labels

# COMBINE THIS WITH UPDATE LABEL DIRECTORY
on:
  workflow_dispatch:

jobs:
  vrms_data:
    runs-on: ubuntu-latest

    if: github.repository == 't-will-gillis/website'

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.HACKFORLA_MIMIC }}

    # Use an action (`my-action`) in your repository
    - name: Save my_data_bs.json
      run: curl -o _data/external/my_data_bs.json https://www.vrms.io/api/recurringevents

    - uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        # Optional glob pattern of files which should be added to the commit
        file_pattern: _data/external/my_data_bs.json
        commit_message: Testing Labels
