name: Lint SCSS

on:
  pull_request:
    branches: [test-5068-august-move-stylelint]
  push:
    branches: [test-5068-august-move-stylelint]

jobs:
  build:
    name: Lint SCSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint SCSS
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: test-5068-august-move-stylelint
          GITHUB_TOKEN: ${{ secrets.TEST_GHAS }}


   
          CSS_FILE_NAME: .stylelintrc.json
          VALIDATE_CSS: true
