name: Move Closed Issues
on:
  issues:
    types:
      - closed
jobs:
  move-closed-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sort Closed Issues by Label
        uses: actions/github-script@v4
        id: sort-closed-issues
        with:
          script: |
            const script = require('./github-actions/move-closed-issues/sort-closed-issues.js')
            const sortIssues = script({context})
            return sortIssues
          result-encoding: string
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Project Board
          column: ${{ steps.sort-closed-issues.outputs.result }}
          repo-token: ${{ secrets.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 }}
