name: Check Member
on: 
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs: 
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Check if PR author is team member
      - name: Verify membership
        id: verify-membership
        uses: actions/github-script@v7     
        with:
          github-token: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
          script: |
            const PR_AUTHOR = context.payload.sender.login;
            const PR_NUMBER = context.payload.number;
            const TEAM = 'website-write';
            const script = require('./github-actions/utils/check-team-membership.js');
            return { PR_NUMBER, script({ github, context }, PR_AUTHOR, TEAM ) };

      # Create an artifact with the message
      - name: Create Artifacts
        run: |
          mkdir -p addingMemberInfo/artifact
          echo ${{ steps.verify-membership.outputs.result }} > addingMemberInfo/artifact/artifact.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adding-verify-membership-artifact
          path: addingMemberInfo/artifact/
