name: Pull Request Verification
on:
  pull_request_target:
    types: [opened]


jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      # Verify membership
      - name: Verify membership
        id: verify-membership
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
          script: |
            const script = require('./github-actions/pr-verification/accept-pr.js')
            script({g: github, c: context})
            
          
