name: Pull Request Verification
on:
  pull_request:
    types: [opened]
    branches:
      - 'gh-pages'

jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Verify membership
      - name: Verify membership
        id: verify-membership
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/pr-verification/accept-pr.js')
            return script({g: github, c: context})
            
          
