name: Pull Request Verification
on:
  pull_request_target:
    types: [opened]

jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:

          script: |
            const verifyPR = require('./github-actions/trigger-pr-target/verify-pr.js');
            verifyPR({github, context});
