name: Pull Request Verification
on:
  pull_request:
    types: [opened]

jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/trigger-pr-target/verify-membership.js');
            result = script({ github, context });
            return result

        
