name: Pull Request Verification
on:
  pull_request:
    types: [opened]

jobs:
  Check-Team-Membership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify PR
        id: verify-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
          script: |
            const script = require('./github-actions/trigger-pr-target/verify-pr.js');
            const result = script({ github, context });
            return result

      - name: Save PR check
        id: save-pr-check
        run: |
          mkdir -p '${{ env.ARTIFACT_DIR }}'
          echo ${{ steps.verify-pr.result }} > '${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_FILE }}'
      
      - name: Upload PR result
      - id: upload-pr-result
        uses: actions/upload-artifact@v4
        with:
          name: pr-check
          path: '${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_FILE }}'
          retention-days: 1
