name: Find Prework Issue and Comment User Activity

on:
  workflow_call:

jobs:
  Add-Comment-To-Prework-Issue-Reusable:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Get activity detail
        id: get-activity-detail
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework-issue-reusable-workflow/get-activity-detail.js')
            const contributor = script({g: github, c: context})
            return contributor

      - if: ${{ steps.get-activity-detail.outputs.result }}
        name: Get prework issue
        id: get-prework-issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework-issue-reusable-workflow/get-prework-issue.js')
            const activityDetail = ${{steps.get-activity-detail.outputs.result}}
            return script({g: github, c: context}, activityDetail)

      - if: ${{ steps.get-prework-issue.ouputs.result }}
        name: Update prework issue status
        id: update-prework-issue-status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          script: |
            const script = require('./github-actions/prework-issue-reusable-workflow/update-prework-issue-status.js')
            const issue = ${{steps.get-prework-issue.outputs.result}}
            return script({g: github, c: context}, issue)
     

      # Only move issue if issue was closed and is reopened
      - name: Move issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          # NOTE: The projectColumnId is hard-coded
          script: |
            const projectColumnId = "MDEzOlByb2plY3RDb2x1bW43MTk4MjI4"
            const issue = ${{steps.update-prework-issue-status.outputs.result}}
            const script = require('./github-actions/utils/update-issue-project-card.js')
             
      - if: ${{ steps.get-prework-issue.outputs.result }} &&  ${{ steps.get-activity-detail.outputs.result }}
        name: Leave comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/add-prework-comment.js')
            const issue = ${{steps.get-prework-issue.outputs.result}}
            const activityDetail = ${{steps.get-activity-detail.outputs.result}}
            script({ g: github, c: context}, issue.number, activityDetail)
          
