name: Schedule Thursday 1100


# Run this action at 11:00 (3 am Pacific) on the first Thursday of the month.
on:
  schedule:
    - cron:  0 11 * * 4 
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "trim_contributors"
  trim_contributors:
    runs-on: ubuntu-latest

    if: github.repository == 't-will-gillis'/website'

    steps:   
    # checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TEST_GHAS }}

    # setup node 
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    # install dependencies to run js file
    - name: Install npm dependencies
      run: npm install
      working-directory: ./github-actions/trigger-schedule/github-data

    # run js file if it is the first Thursday of the month
    - name: Trim Members
      env:
        token: ${{ secrets.TEST_GHAS }}
      run: node github-actions/trigger-schedule/github-data/contributors-data.js
