name: Update Label Directory

# This action updates github-actions/utils/_data/label-directory.json
on:
  label:
    types: [edited, created, deleted]

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'
    
    steps:
     - uses: actions/checkout@v4
     - name: Dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }} 
       run: echo "GITHUB_CONTEXT defined"
    
     - name: Update label directory
       id: update-label-directory
       uses: actions/github-script@v7
       with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/utils/update-label-directory.js')
          const results = script({g: github, c: context})
          return results

     - name: Send POST request to Google Apps Script
       run: |
         curl -X POST "https://script.google.com/macros/s/AKfycbycZV2uZ8SCIbM5hjOB3iw1Gvtx3JrX4oV1nzY8LFdJtqUpoTxfi6VqJVH4uNzEPeCC/exec" \
           -H "Content-Type: application/json" \
           -d '{"repository": {"full_name": "user/repo"}, "pusher": {"name": "username"}, "head_commit": {"message": "Test commit message"}}'
       
     - name: Commit changes
       uses: stefanzweifel/git-auto-commit-action@v5.0.0
       with:
         # Glob pattern of file to commit, and opt. commit message + author
         file_pattern: github-actions/utils/_data/label-directory.json
         commit_message: Update label directory
         commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org> 
