name: Update Label Directory

# This action runs when changes are made to Labels
on:
  label:
    types: edited

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'
    
    steps:
     - name: dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT['label']" 
     

