name: Update Label Directory

# This action runs when changes are made to Labels
on:
  label:
    types: edited

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'
    
    steps:
     - uses: actions/checkout@v4
     
     - name: dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT" 
   
     - name: send context
       uses: actions/github-script@v7
       id: send-context
       with:
        github-token: ${{ secrets.HACKFORLA_MIMIC }}
        script: |
          const artifactContent = process.env.GITHUB_CONTEXT
          const script = require('./github-actions/utils/return-label-name.js')
          script({g: github, c: context}, artifactContent)
     
     - name: third time
       env:
         GITHUB_CONTEXT_NUTHER: ${{ toJson(github) }}
       run: |
         echo "THIRD_TIME=$(cat GITHUB_CONTEXT_NUTHER)" >> $GITHUB_ENV
