name: Update Label Directory

# This action updates github-actions/utils/_data/label-directory.json
on:
  label:
    types: [edited, created, deleted]

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'
    
    steps:
     - uses: actions/checkout@v4
     - name: Dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }} 
       run: echo "GITHUB_CONTEXT defined"
    
     - name: Update label directory
       id: update-label-directory
       uses: actions/github-script@v7
       with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/utils/update-label-directory.js')
          const labelPacket = script({g: github, c: context})
          return labelPacket

     # Note the the URL below match the Google Apps spreadsheet that tracks label changes. If something is broken, check this link
     - name: Send POST request to Google Apps Script
       if: steps.update-label-directory.outputs.result != ''
       run: |
         curl -X POST "https://script.google.com/macros/s/AKfycbwL7d4roCikv6mo5icTKRGOTCZk8up3oe0x5KPTRseQ9ePCL1cMqpPpFc62d1GEXQC7/exec" \
           -H "Content-Type: application/json" \
           -d '${{ steps.update-label-directory.outputs.result }}'
       
     - name: Commit changes
       uses: stefanzweifel/git-auto-commit-action@v5.0.1
       with:
         # Glob pattern of file to commit, and opt. commit message + author
         file_pattern: github-actions/utils/_data/label-directory.json
         commit_message: Update label directory
         commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org> 
