name: Update Label Directory

# This action triggered by change to Labels, updates github-actions/utils/_data/label_directory.json
on:
  label:
    types: [edited, created]

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    if: github.repository == 't-will-gillis/website'
    
    steps:
     - uses: actions/checkout@v4
     - name: dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }} 
       run: echo "GITHUB_CONTEXT defined"
    
     - name: send context
       uses: actions/github-script@v7
       id: send-context
       with:
        github-token: ${{ secrets.HACKFORLA_MIMIC }}
        script: |
          const script = require('./github-actions/utils/label_update_name.js')
          script({g: github, c: context})

     - name: update label directory
       uses: stefanzweifel/git-auto-commit-action@v5.0.0
       with:
         # Glob pattern of file which should be added to the commit
         file_pattern: github-actions/utils/_data/label_directory.json
         
         # Optional commit message and author settings
         commit_message: Update label directory
         commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org> 
