name: WR Pull Request Trigger
on:
  workflow_run:
    workflows: ["Pull Request Trigger"]
    types: [completed]

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for keyword and issue number
      id: check-for-keyword
      uses: actions/github-script@v7
      with:
        # github-token: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
        script: |
          const script = require('./github-actions/trigger-pr/check-linked-issue.js')
          script({g: github, c: context})
