name: WR PR Verification
on:
  workflow_run:
    workflows: ['PR Verification']
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The PR Verification workflow failed. Please check the logs.'
      - run: exit 1
      
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The PR Verification workflow succeeded. The workflow will continue.'
  
  after-verification:
    needs: on-success
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: 'verify-pr'
      SCRIPT_PATH: './github-actions/trigger-pr-target/verify-pr.js'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact
        id: download-artifact
        uses: actions/github-script@v7
        with:
          script: |
            const { downloadLabelsArtifact } = require('${{ env.SCRIPT_PATH }}');
            await downloadLabelsArtifact({ github, context }, '${{ env.ARTIFACT_NAME }}');
            
      - name: Extract artifact
        id: extract-artifact
        run: unzip '${{ env.ARTIFACT_NAME }}.zip'

      - name: Close and 
        uses: actions/github-script@v7
        with:
          script: |
            const { setLabelsOnPR } = require('${{ env.SCRIPT_PATH }}');
            await setLabelsOnPR({ github, context, core }, '${{ env.ARTIFACT_NAME }}.json');
